jpg=Images
jpeg=Images
png=Images
gif=Images
bmp=Images
webp=Images

pdf=Documents
doc=Documents
docx=Documents
txt=Documents
ppt=PPT
pptx=PPT
xls=Excel
xlsx=Excel

zip=Archives
rar=Archives
7z=Archives
tar=Archives

mp3=Music
wav=Music
aac=Music

mp4=Videos
avi=Videos
mkv=Videos
mov=Videos

exe=Programs
msi=Programs